[project]
name = "rheadb"
version = "0.0.1"
authors = [
  { name="Anastasia Sveshnikova", email="anastasia.sveshnikova@sib.swiss" },
]
description = "Package to facilitate cheminformatics access to RheaDB and its analysis with Python"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/sib-swiss/rheadb"
Issues = "https://github.com/sib-swiss/rheadbissues"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"