name: Tests
on: [push, pull_request, workflow_call, workflow_dispatch]

jobs:

  CodeQL-Analysis:
    name: CodeQL analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      packages: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:python"

  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os:
        - ubuntu-latest
        # - macos
        # - windows

    steps:
    - uses: actions/checkout@v4

    - name: 🐍 Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: 📥️ Install dependencies
      run: |
        pip install -e ".[test]"

    - name: ☑️ Test with coverage
      run: |
        pytest --cov-report xml

    - name: ☂️ Upload coverage to Coveralls
      uses: coverallsapp/github-action@v2
